### ISSUE TITLE
Rearrange project structure

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/demo_dbt_airflow#2]
Task:https://n-abledev.atlassian.net/browse/DA-2564?atlOrigin=eyJpIjoiMWE0NGMxMTFjNGE0NGRkMjkxODFkZmQzYjljZTAyN2EiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #5 from koshitha-nable/ka/feature/002/rearrange_project_structure
