### ISSUE TITLE
Create readme file explaining all steps

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/demo_dbt_airflow#3]
Task : https://n-abledev.atlassian.net/browse/DA-2564?atlOrigin=eyJpIjoiMTc1NTMzMzg3YWU5NGEyZGIzYmM3Yzk2OGE4MGRlMTciLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #4 from koshitha-nable/ka/feature/003/create_readme_file
